name: movieapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.0.0
  # Value equality
  equatable: ^1.0.2
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: 0.12.0+4
  # Local cache
  shared_preferences: ^0.5.6
  #Cupertino icons
  cupertino_icons: ^0.1.3
  #Rating bar
  flutter_rating_bar: ^3.0.0+1
  #YouTube player
  youtube_player_flutter: ^6.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:

  uses-material-design: true

  fonts:
   - family: McLaren
     fonts:
       - asset: fonts/McLaren-Regular.ttf
